### ISSUE TITLE
[Feature / NotImple] 사용자 1:1문의 게시판 글 등록

### ISSUE THREAD

**Issue by lucinda96** [ssg-240304-java2/shop-notImplement#2]
## 📜 Description

사용자 화면의 마이페이지에서 1:1문의를 등록하는 기능 작성

## 🌈 Success criteria

1.  사용자 1:1문의 화면 표시
2.  제목,내용 미입력시 에러메세지 표시, 입력 시 DB저장
3.  DB에 입력한 내용 등록되어있을것

## 👷 To-do

- [ ] 사용자 마이페이지에 1:1문의 메뉴추가
- [ ] 1:1문의 목록화면에 등록버튼 추가
- [x] 1:1문의 예외처리(제목, 내용 미입력시 에러메세지 표시)
- [x] 1:1문의  DB등록 처리
- [x] 1:1문의 등록완료 메세지 표시

##  🔗Related issues

Related to:
