### ISSUE TITLE
[Feature / NotImple] 관리자 주문 정보 조회

### ISSUE THREAD

**Issue by jisoo78** [ssg-240304-java2/shop-notImplement#22]
## 📜 Description

관리자는 구매자가 주문한 상품의 주문정보를 조회할 수 있다
## 🌈 Success criteria

1. 관리자 화면에 주문 정보 조회 화면을 표시
2. 주소지는 시,도로 끝나는 것을 표시한다
3. 상세보기 선택시 새로운 화면으로 넘어가 상세정보를 불러올 수 있다
## 👷 To-do

- [x] 주문 정보 조회 화면을 구현
- [x] 주소지 DB에서 받아오기
- [x]  버튼 선택시-->(대쉬보드 선택시)상세정보 화면으로 이동
- [x] DB에 저장된 상세정보 불러오기
##  🔗Related issues

Related to: #이슈번호
