### ISSUE TITLE
[Feature / NotImple] 구매자 주문서 작성

### ISSUE THREAD

**Issue by jisoo78** [ssg-240304-java2/shop-notImplement#24]
## 📜 Description

구매자가 상품 렌탈시 주문서를 작성하는 기능 구현
## 🌈 Success criteria

1. 주문서 화면 구현시 상품에서 상품명과 select box 불러오기
2. DB에서 주소지 불러와 화면에 띄우기 
3. 휴대전화정보 DB에서 불러오기
4.  결제시 주문상태는 결제완료로 처리
## 👷 To-do

- [x] 주문서 작성시 화면 구현과 상품명과 렌탈기간 가격 불러오기
- [x] 주소 DB에서 받아오기
- [x] 휴대전화 DB에서 받아오기
- [x] 주문배송조회시 주문상태는 결제완료로 처리 
- [x] 주문번호와 함께 DB에 저장
##  🔗Related issues

Related to: #이슈번호
