### ISSUE TITLE
[Feature / NotImple] 사용자 1:1 문의 게시판 글 조회

### ISSUE THREAD

**Issue by lucinda96** [ssg-240304-java2/shop-notImplement#27]
## 📜 Description

로그인한 사용자가 등록한 1:1문의 내용을 화면에 표시하는 기능입니다.
 

## 🌈 Success criteria

1. 등록된 1:1문의글의 내용 조회
2. 답글이있는경우 답글표시, 없는 경우 문의 내용만 표시

## 👷 To-do

- [ ] 1:1문의 조회 화면 만들기
- [x] 1:1 문의 데이터 화면표시
- [ ] 답변이 여부에 따라 답변 부분 표시 미표시 진행
- [ ] 목록버튼 클릭 시 1:1문의 목록화면 이동

##  🔗Related issues

Related to: #이슈번호
