### ISSUE TITLE
[Feature / NotImple] 사용자 1:1문의 목록 

### ISSUE THREAD

**Issue by lucinda96** [ssg-240304-java2/shop-notImplement#28]
## 📜 Description

마이페이지에서 1:1문의 클릭시 1:1문의 목록 표시

## 🌈 Success criteria

1. 마이페이지에서 메뉴 클릭시 등록한 글이 목록으로 표시
2. 등록된 글이 없는경우 '등록된 글이 없습니다' 표시

## 👷 To-do

- [x] 1:1문의 목록화면 작성(No | 문의 제목 | 답변여부 | 문의 등록일)
- [ ] 1:1문의 목록에서 제목 클릭시 상세화면 이동
- [ ] 등록버튼 클릭시 등록화면으로 이동

##  🔗Related issues

Related to: #31
