### ISSUE TITLE
[Feature / NotImple] 관리자 상품 대시보드

### ISSUE THREAD

**Issue by zZerorok** [ssg-240304-java2/shop-notImplement#3]
## 📜 Description

관리자 페이지에서 상품 현황 대시보드 화면 구현

## 🌈 Success criteria

대시보드에서 3가지 항목 표시
1. 전체 상품
2. 렌탈 가능 상품
3. 품절 상품

## 👷 To-do

- [x] 상품 대시보드 메뉴 추가
- [x] 전체 상품 수량 표시
- [x] 렌탈 가능 상품 수량 표시
- [x] 품절 상품 수량 표시

##  🔗Related issues

Related to:
