### ISSUE TITLE
[Feature / NotImple] 사용자/관리자 상품리뷰 상세페이지 조회

### ISSUE THREAD

**Issue by lucinda96** [ssg-240304-java2/shop-notImplement#36]
## 📜 Description

등록한 상품 리뷰 선택 시 상세 페이지에 등록된 리뷰내용 표시

## 🌈 Success criteria

1. 등록된 리뷰 내용 표시
2. 수정,목록 버튼 클릭 시 화면이동

## 👷 To-do

- [ ] 등록한 상품 리뷰 정보가 화면에 표시된다.
- [ ] 수정 버튼 클릭 시 화면 이동
- [ ] 목록 버튼 클릭 시 화면이동

##  🔗Related issues

Related to: #이슈번호
