### ISSUE TITLE
[Feature / NotImple] 관리자 상품 삭제

### ISSUE THREAD

**Issue by zZerorok** [ssg-240304-java2/shop-notImplement#7]
## 📜 Description

관리자 페이지에서 상품을 삭제하는 기능

## 🌈 Success criteria

1. 상품을 삭제하면 DB에 저장되어 있는 상품이 삭제됩니다.

## 👷 To-do

 - [x] 상품 삭제 버튼 추가
 - [x] 상품 삭제 추가 확인
 - [x] DB에 저장되어 있는 상품 삭제

##  🔗Related issues

Related to: #이슈번호
