### ISSUE TITLE
[Feature / NotImple] 사용자 상품 상세 정보

### ISSUE THREAD

**Issue by zZerorok** [ssg-240304-java2/shop-notImplement#9]
## 📜 Description

사용자 페이지에서 상품 상세 정보 화면 표시

## 🌈 Success criteria

1. DB에 저장된 상품 상세 정보 표시
2. 렌탈 기간은 사용자가 선택할 수 있다.
3. 선택한 렌탈 기간과 상품 정보 표시
4. 렌탈 진행 시 선택한 상품 정보 넘겨주기

## 👷 To-do

- [x] 상품 상세 정보 페이지 추가
- [x] 렌탈하기 버튼 추가
- [x] 렌탈 기간(1개월 ~ 6개월)과 가격 표시된 select box 구현
- [x] 상품 상세 정보 표시(상품명, 브랜드, 가격, 상품 설명)

##  🔗Related issues

Related to: #이슈번호
